#!/usr/bin/env python3

'''
Riceve una lista di files da linea di comando
Invia i loro contenuti tramite server socket
'''

import struct, socket, concurrent.futures, threading
import os, sys

HOST = "127.0.0.1"
PORT = 51433

def main(file_list):
    with concurrent.futures.ThreadPoolExecutor(max_workers=5) as executor:
        for file in file_list:
            executor.submit(invia_file, file)

def invia_file(file):
    if not os.path.exists(file):
        print("Il file %s non esiste", file)
        return
    with open(file, "r") as f:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.connect((HOST, PORT))
            print(f"{threading.current_thread().name} Connesso a", s.getpeername())
            # pronto per inviare la richiesta
            b = str.encode("B")
            s.sendall(struct.pack("c", b))
            for linea in f:
                line = linea.encode()
                lunghezza = len(line);
                s.sendall(struct.pack("<h", lunghezza))
                for carattere in line:
                    s.sendall(struct.pack("b", carattere))
                print(f"{threading.current_thread().name} Inviato con successo.")
            print(f"{threading.current_thread().name} -- Inviato intero file.\n Invio il segnale di terminazione.")
            lunghezza = 0
            s.sendall(struct.pack("<h", lunghezza))
            s.shutdown(socket.SHUT_RDWR)

if len(sys.argv) < 2:
    print("Uso: client2 file1, file2 ...")
else:
    main(sys.argv[1:])
